### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([94, 57, 48, 23, 23, 45, 88, 38, 89, 33, 54, 96, 53, 50, 30])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[21, 34, 88, 18],
       [28, 98,  4, 95],
       [35, 22, 41, 86],
       [42, 64, 56, 64],
       [45, 35, 97,  3],
       [16, 63, 88, 81]])

In [3]:
np.sort(a)[::-1]

array([96, 94, 89, 88, 57, 54, 53, 50, 48, 45, 38, 33, 30, 23, 23])

In [4]:
np.sort(b,axis=0)

array([[16, 22,  4,  3],
       [21, 34, 41, 18],
       [28, 35, 56, 64],
       [35, 63, 88, 81],
       [42, 64, 88, 86],
       [45, 98, 97, 95]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
# code
np.append(a,200)

array([ 94,  57,  48,  23,  23,  45,  88,  38,  89,  33,  54,  96,  53,
        50,  30, 200])

In [6]:
b

array([[21, 34, 88, 18],
       [28, 98,  4, 95],
       [35, 22, 41, 86],
       [42, 64, 56, 64],
       [45, 35, 97,  3],
       [16, 63, 88, 81]])

In [7]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[2.10000000e+01, 3.40000000e+01, 8.80000000e+01, 1.80000000e+01,
        5.23310896e-01],
       [2.80000000e+01, 9.80000000e+01, 4.00000000e+00, 9.50000000e+01,
        4.43177883e-01],
       [3.50000000e+01, 2.20000000e+01, 4.10000000e+01, 8.60000000e+01,
        8.42121734e-01],
       [4.20000000e+01, 6.40000000e+01, 5.60000000e+01, 6.40000000e+01,
        3.11654848e-02],
       [4.50000000e+01, 3.50000000e+01, 9.70000000e+01, 3.00000000e+00,
        3.57561407e-01],
       [1.60000000e+01, 6.30000000e+01, 8.80000000e+01, 8.10000000e+01,
        3.04615378e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [11]:
# code
a.shape

(15,)

In [12]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [13]:
np.expand_dims(a,axis=1)

array([[94],
       [57],
       [48],
       [23],
       [23],
       [45],
       [88],
       [38],
       [89],
       [33],
       [54],
       [96],
       [53],
       [50],
       [30]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  6,  7, 10, 12]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([11,  0, 28, 50, 38, 37,  0,  0,  5, 30,  0,  9,  0,  2, 21])

In [ ]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [14]:
# code
a

array([94, 57, 48, 23, 23, 45, 88, 38, 89, 33, 54, 96, 53, 50, 30])

In [15]:
np.argmax(a)

11

In [16]:
b

array([[21, 34, 88, 18],
       [28, 98,  4, 95],
       [35, 22, 41, 86],
       [42, 64, 56, 64],
       [45, 35, 97,  3],
       [16, 63, 88, 81]])

In [17]:
np.argmax(b,axis=0)

array([4, 1, 4, 1])

In [18]:
np.argmax(b,axis=1)

array([2, 1, 3, 1, 2, 2])

In [19]:
# np.argmin
np.argmin(a)

3

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [20]:
a

array([94, 57, 48, 23, 23, 45, 88, 38, 89, 33, 54, 96, 53, 50, 30])

In [21]:
np.cumsum(a)

array([ 94, 151, 199, 222, 245, 290, 378, 416, 505, 538, 592, 688, 741,
       791, 821])

In [22]:
b

array([[21, 34, 88, 18],
       [28, 98,  4, 95],
       [35, 22, 41, 86],
       [42, 64, 56, 64],
       [45, 35, 97,  3],
       [16, 63, 88, 81]])

In [23]:
np.cumsum(b,axis=1)

array([[ 21,  55, 143, 161],
       [ 28, 126, 130, 225],
       [ 35,  57,  98, 184],
       [ 42, 106, 162, 226],
       [ 45,  80, 177, 180],
       [ 16,  79, 167, 248]])

In [24]:
np.cumsum(b)

array([  21,   55,  143,  161,  189,  287,  291,  386,  421,  443,  484,
        570,  612,  676,  732,  796,  841,  876,  973,  976,  992, 1055,
       1143, 1224])

In [25]:
# np.cumprod
np.cumprod(a)

array([                  94,                 5358,               257184,
                    5915232,            136050336,           6122265120,
               538759330560,       20472854561280,     1822084055953920,
          60128773846479360,  3246953787709885440, -1887085632913375232,
       -7781818175861129216, -1709283245155876864,  4061734866452348928])

In [26]:
a

array([94, 57, 48, 23, 23, 45, 88, 38, 89, 33, 54, 96, 53, 50, 30])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [27]:
a

array([94, 57, 48, 23, 23, 45, 88, 38, 89, 33, 54, 96, 53, 50, 30])

In [32]:
np.percentile(a,89)

91.30000000000001

In [33]:
np.median(a)

50.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [34]:
# code
a

array([94, 57, 48, 23, 23, 45, 88, 38, 89, 33, 54, 96, 53, 50, 30])

In [36]:
np.histogram(a,bins=[0,20,40,60,80,100])

(array([0, 5, 6, 0, 4]), array([  0,  20,  40,  60,  80, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [37]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [38]:
# code
a


array([94, 57, 48, 23, 23, 45, 88, 38, 89, 33, 54, 96, 53, 50, 30])

In [39]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([50, 30])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [40]:
# code
a

array([94, 57, 48, 23, 23, 45, 88, 38, 89, 33, 54, 96, 53, 50, 30])

In [41]:
np.flip(a)

array([30, 50, 53, 96, 54, 33, 89, 38, 88, 45, 23, 23, 48, 57, 94])

In [42]:
b

array([[21, 34, 88, 18],
       [28, 98,  4, 95],
       [35, 22, 41, 86],
       [42, 64, 56, 64],
       [45, 35, 97,  3],
       [16, 63, 88, 81]])

In [45]:
np.flip(b,axis=1)

array([[18, 88, 34, 21],
       [95,  4, 98, 28],
       [86, 41, 22, 35],
       [64, 56, 64, 42],
       [ 3, 97, 35, 45],
       [81, 88, 63, 16]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [46]:
# code
a

array([94, 57, 48, 23, 23, 45, 88, 38, 89, 33, 54, 96, 53, 50, 30])

In [47]:
np.put(a,[0,1],[110,530])

In [48]:
a

array([110, 530,  48,  23,  23,  45,  88,  38,  89,  33,  54,  96,  53,
        50,  30])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [49]:
# code
a

array([110, 530,  48,  23,  23,  45,  88,  38,  89,  33,  54,  96,  53,
        50,  30])

In [50]:
np.delete(a,[0,2,4])

array([530,  23,  45,  88,  38,  89,  33,  54,  96,  53,  50,  30])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [51]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
np.intersect1d(m,n)

array([3, 4, 5])

In [53]:
np.setdiff1d(n,m)

array([6, 7])

In [54]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [55]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [64]:
# code
a

array([110, 530,  48,  23,  23,  45,  88,  38,  89,  33,  54,  96,  53,
        50,  30])

In [65]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 48, 25, 25, 45, 75, 38, 75, 33, 54, 75, 53, 50, 30])

In [58]:
# 17. np.swapaxes

In [59]:
# 18. np.uniform

In [60]:
# 19. np.count_nonzero

In [61]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [62]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [63]:

# 25. np.allclose and equals